name: Deploy

# masterでコミットが発生した場合に実行する
on:
  push:
    branches:
      - master

jobs:
  sample:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1

      # 特定のディレクトリ以下を GitHub Pages に公開するアクションを利用
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        # 公開する資源の設定
        with:

          # デプロイに利用する認証情報
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # 公開するディレクトリ
          publish_dir: ./html
