name: Omuraisu

on: push

jobs:
  shitajunbi:
    runs-on: macos-10.15
    steps:
      - name: warm_rice
        run: echo Gohan wo Atatameru

      - name: beat_egg
        run: echo Tamago wo Toku

  cook_omelette:
    runs-on: macos-10.15
    steps:
      - name: bake_egg
        run: echo Tamago wo Yaku

  cook_ketchup_rice:
    runs-on: macos-10.15
    steps:
      - name: itameru
        run: echo Gohan wo Ireru
        run: echo Ketchup wo Ireru
        run: echo Iikanji ni Itameru

  omelette_rice:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1

      - name: egg_on_rice
        run: echo Tamago wo Gohan ni Noseru

      - name: finish
        run: bash ./finish.sh
