# Workflow名（好きな名前でOK）
# "ケーキの作り方"みたいな
name: Sample

# 実行するタイミング (github に push があったタイミングで実行する)
on: push

# 実行する処理の設定
jobs:

  # 実行する処理の名前
  # "下準備"みたいな
  sample:

    # 実行する環境（ macOS の 10.15 を利用 ）
    runs-on: macos-10.15

    # 実行する処理やコマンドの指定
    steps:
      # リポジトリからファイルを取得するアクションを利用
      # - uses: actions/checkout@v1

      # Hello, World! を表示する
      - name: Sample
        # "オーブンをあたためる"みたいな
        # run: echo Hello, World!
        # run: bash ./print_hello.sh
        run: bash sample.yml

      # - name: Sample
      # "いちごを洗って切る"みたいな
      # 並行作業もまとめて書くのがミソ
      # run: echo Hello, World!
